import type { Metadata } from 'next';
import localFont from 'next/font/local';
import { Inter, Hanken_Grotesk } from 'next/font/google';
import Image from 'next/image';
import './globals.css';
import { cn } from '@/utils/cn';
import { DockMenu, Footer } from './_components';

export const metadata: Metadata = {
  title: 'Raimov Xushnudbek personal blogs (X-Blogs)',
  description: 'Generated by create next app',
};

const inter = Inter({
  subsets: ['latin'],
  display: 'swap',
  weight: ['400', '500', '600'],
  variable: '--font-inter',
});

const hankenGrotesk = Hanken_Grotesk({
  subsets: ['latin'],
  display: 'swap',
  weight: ['400', '500', '600'],
  variable: '--font-hanken-grotesk',
});

const satoshi = localFont({
  src: [
    {
      path: '../../public/font/Satoshi-Regular.woff2',
      weight: '400',
      style: 'normal',
    },
    {
      path: '../../public/font/Satoshi-Medium.woff2',
      weight: '500',
      style: 'normal',
    },
  ],
  display: 'swap',
  variable: '--font-satoshi',
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        cz-shortcut-listen="true"
        className={cn(
          'bg-cod-gray relative',
          inter.variable,
          satoshi.variable,
          hankenGrotesk.variable,
        )}
      >
        <Image src="/Container.png" alt="noise" fill className="z-[1]" />
        <div>{children}</div>
        <Footer />
        <div className="fixed bottom-[10px] left-1/2 z-20 -translate-x-1/2">
          <DockMenu />
        </div>
        {/* <Menu /> */}
      </body>
    </html>
  );
}
